/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author agustin
 */
public class GuiCRUDAdmin extends javax.swing.JInternalFrame{

    /**
     * Creates new form GuiCRUDAdmin2
     */
    public GuiCRUDAdmin() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreate = new javax.swing.JToggleButton();
        btnModify = new javax.swing.JToggleButton();
        btnDelete = new javax.swing.JToggleButton();
        lblName = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        lblMessage = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Opciones de Administrador");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        btnCreate.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        btnCreate.setText("Crear Administrador");

        btnModify.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        btnModify.setText("Modificar");

        btnDelete.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        btnDelete.setText("Borrar Administrador");
        btnDelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnDeleteKeyTyped(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        lblName.setText("Nombre");

        lblPass.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        lblPass.setText("Contraseña");

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });

        passField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passFieldKeyTyped(evt);
            }
        });

        lblMessage.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText("Seleccione una opcion: Crear, modificar o borrar");

        btnConfirm.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        btnConfirm.setText("Listo");
        btnConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnConfirmKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnCreate))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPass)
                            .addComponent(lblName))
                        .addGap(17, 17, 17)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPass)))
                    .addComponent(btnConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
         if(evt.getKeyChar() == KeyEvent.VK_ENTER)
            btnConfirm.doClick();
    }//GEN-LAST:event_txtNameKeyTyped

    private void passFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passFieldKeyTyped
         if(evt.getKeyChar() == KeyEvent.VK_ENTER)
            btnConfirm.doClick();
    }//GEN-LAST:event_passFieldKeyTyped

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_ENTER)
           btnConfirm.doClick();
    }//GEN-LAST:event_formKeyTyped

    private void btnDeleteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDeleteKeyTyped
       /* if(evt.getKeyChar() == KeyEvent.VK_ENTER)
           btnConfirm.doClick();*/
    }//GEN-LAST:event_btnDeleteKeyTyped

    private void btnConfirmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConfirmKeyTyped
        if(evt.getKeyChar() == KeyEvent.VK_ENTER)
           btnConfirm.doClick();
    }//GEN-LAST:event_btnConfirmKeyTyped

    
    
    public JButton getBtnConfirm() {
        return btnConfirm;
    }

    public JToggleButton getBtnCreate() {
        return btnCreate;
    }

    public JToggleButton getBtnDelete() {
        return btnDelete;
    }

    public JToggleButton getBtnModify() {
        return btnModify;
    }

    public JLabel getLblMessage() {
        return lblMessage;
    }

    public JLabel getLblName() {
        return lblName;
    }

    public JLabel getLblPass() {
        return lblPass;
    }

    public JPasswordField getPassField() {
        return passField;
    }

    public JTextField getTxtName() {
        return txtName;
    }
    
    /**
     * Change the title of the screen
     * @param newMessage new message to be setted
     */
    public void setLblMessage(String newMessage) {
        lblMessage.setText(newMessage);
    }
    
    
    /**
     * clean all the text fields
     * 
     */
    public void cleanFields(){
        passField.setText("");
        txtName.setText("");
    }
    
    /**
     * Set an action listener for all buttons of this class
     * @param ac new action listener to be added
     */
    public void setActionListener(ActionListener ac){
        btnCreate.addActionListener(ac);
        btnConfirm.addActionListener(ac);
        btnDelete.addActionListener(ac);
        btnModify.addActionListener(ac);
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JToggleButton btnCreate;
    private javax.swing.JToggleButton btnDelete;
    private javax.swing.JToggleButton btnModify;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JPasswordField passField;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

}
