/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.order;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JTextArea;

/**
 *
 * @author nico
 */
public class GuiBarOrderPane extends javax.swing.JPanel {

    private int position;

    /**
     * Creates new form orderPane
     *
     * @param orderId id del pedido.
     * @param orderDescription descripción del pedido.
     * @param orderArrivalTime tiempo de llegada del pedido.
     */
    public GuiBarOrderPane() {
        initComponents();
    }

    public GuiBarOrderPane(String orderName, String desc, String date) {
        orderNumber.setText(orderName);
        timeOrderArrival.setText(date);
        txtOrderDescription.setText(desc);
        initComponents();
    }

    /**
     * setea el color del panel 0 blanco, 1 verde, 2 amarillo, 3 rojo
     *
     * @param color
     */
    public void setColor(int color) {
        switch (color) {
            case 0:
                setBackground(Color.WHITE);
                txtOrderDescription.setBackground(Color.WHITE);
                break;
            case 1:
                setBackground(new java.awt.Color(25, 169, 42));
                txtOrderDescription.setBackground(new java.awt.Color(25, 169, 42));
                break;
            case 2:
                setBackground(new java.awt.Color(253, 216, 47));
                txtOrderDescription.setBackground(new java.awt.Color(253, 216, 47));
                break;
            case 3:
                setBackground(new java.awt.Color(251, 28, 4));
                txtOrderDescription.setBackground(new java.awt.Color(251, 28, 4));
                break;
        }
    }

    /**
     * Devuelve el label que debe mostrar el número del pedido.
     *
     * @return the orderNumber
     */
    public javax.swing.JLabel getOrderNumber() {
        return orderNumber;
    }

    /**
     * Devuelve el label que debe mostrar el tiempo de llegada del pedido.
     *
     * @return the timeOrderArrival
     */
    public javax.swing.JLabel getTimeOrderArrival() {
        return timeOrderArrival;
    }

    /**
     * Devuelve el text area que contiene la descripción del pedido.
     *
     * @return the txtOrderDescription
     */
    public JTextArea getTxtOrderDescription() {
        return txtOrderDescription;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtOrderDescription = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        orderNumber = new javax.swing.JLabel();
        timeOrderArrival = new javax.swing.JLabel();
        btnOrderReady = new javax.swing.JButton();
        btnPostpone = new javax.swing.JButton();

        setBackground(new java.awt.Color(253, 216, 47));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(230, 230));
        setMinimumSize(new java.awt.Dimension(230, 230));
        setPreferredSize(new java.awt.Dimension(230, 230));

        txtOrderDescription.setEditable(false);
        txtOrderDescription.setBackground(new java.awt.Color(253, 216, 47));
        txtOrderDescription.setColumns(14);
        txtOrderDescription.setRows(5);
        jScrollPane1.setViewportView(txtOrderDescription);

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel1.setText("Pedido:");

        orderNumber.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        orderNumber.setText("n° de pedido");

        timeOrderArrival.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        timeOrderArrival.setText("Hora de llegada del pedido");

        btnOrderReady.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        btnOrderReady.setText("Pedido Listo");

        btnPostpone.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        btnPostpone.setText("Posponer");
        btnPostpone.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(timeOrderArrival, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(orderNumber))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnOrderReady, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPostpone, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(orderNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeOrderArrival)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPostpone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOrderReady, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrderReady;
    private javax.swing.JButton btnPostpone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orderNumber;
    private javax.swing.JLabel timeOrderArrival;
    private javax.swing.JTextArea txtOrderDescription;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the position
     */
    public int getPosition() {
        return position;
    }

    /**
     * @param position the position to set
     */
    public void setPosition(int position) {
        this.position = position;
    }

    /**
     * @return the btnOrderReady
     */
    public javax.swing.JButton getBtnOrderReady() {
        return btnOrderReady;
    }

    /**
     * @return the btnPostpone
     */
    public javax.swing.JButton getBtnPostpone() {
        return btnPostpone;
    }
    
    public void setActionListener(ActionListener lis){
        this.btnPostpone.addActionListener(lis);
        this.btnOrderReady.addActionListener(lis);
    }
}
