/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui.order;

import java.awt.Color;
import javax.swing.JTextArea;

/**
 *
 * @author nico
 */
public class GuiKitchenOrderPane extends javax.swing.JPanel {

    /**
     * Creates new form orderPane
     * @param orderId id del pedido.
     * @param orderDescription descripción del pedido.
     * @param orderArrivalTime tiempo de llegada del pedido.
     */
    public GuiKitchenOrderPane(String orderId, String orderDescription, String orderArrivalTime) {
        initComponents();
        this.txtOrderDescription.setText(orderDescription);
        this.orderNumber.setText(orderId);
        this.timeOrderArrival.setText(orderArrivalTime);
    }

    /**
     * setea el color del panel 
     * 0 blanco, 1 verde, 2 amarillo, 3 rojo
     * @param color 
     */
    public void setColor(int color){
        switch (color){
           case 0 : 
                    setBackground(Color.WHITE);
                    txtOrderDescription.setBackground(Color.WHITE);
                    break;
           case 1 : 
                    setBackground(new java.awt.Color(25, 169, 42));
                    txtOrderDescription.setBackground(new java.awt.Color(25, 169, 42));
                    break;
           case 2 : 
                    setBackground(new java.awt.Color(253, 216, 47));
                    txtOrderDescription.setBackground(new java.awt.Color(253, 216, 47));
                    break; 
           case 3 : 
                    setBackground(new java.awt.Color(251, 28, 4));
                    txtOrderDescription.setBackground(new java.awt.Color(251, 28, 4));
                    break;      
        }
    }

    /**
     * Devuelve el label que debe mostrar el número del pedido.
     * @return the orderNumber
     */
    public javax.swing.JLabel getOrderNumber() {
        return orderNumber;
    }

    /**
     * Devuelve el label que debe mostrar el tiempo de llegada del pedido.
     * @return the timeOrderArrival
     */
    public javax.swing.JLabel getTimeOrderArrival() {
        return timeOrderArrival;
    }

    /**
     * Devuelve el text area que contiene la descripción del pedido.
     * @return the txtOrderDescription
     */
    public JTextArea getTxtOrderDescription() {
        return txtOrderDescription;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtOrderDescription = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        orderNumber = new javax.swing.JLabel();
        timeOrderArrival = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 216, 47));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(304, 304));
        setMinimumSize(new java.awt.Dimension(304, 304));
        setPreferredSize(new java.awt.Dimension(304, 304));

        txtOrderDescription.setEditable(false);
        txtOrderDescription.setBackground(new java.awt.Color(253, 216, 47));
        txtOrderDescription.setColumns(20);
        txtOrderDescription.setRows(5);
        jScrollPane1.setViewportView(txtOrderDescription);

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel1.setText("Pedido:");

        orderNumber.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        orderNumber.setText("n° de pedido");

        timeOrderArrival.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        timeOrderArrival.setText("Hora de llegada del pedido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderNumber))
                    .addComponent(timeOrderArrival))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(orderNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeOrderArrival)
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orderNumber;
    private javax.swing.JLabel timeOrderArrival;
    private javax.swing.JTextArea txtOrderDescription;
    // End of variables declaration//GEN-END:variables
}
