/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.order;

import javax.swing.JTextArea;

/**
 *
 * @author joako
 */
public class GuiKitchenOrderPane extends javax.swing.JPanel {

    /**
     * Creates new form orderPane
     * @param orderId id del pedido.
     * @param orderDescription descripción del pedido.
     * @param orderArrivalTime tiempo de llegada del pedido.
     */
    public GuiKitchenOrderPane(String orderId, String orderDescription, String orderArrivalTime) {
        this.txtOrderDescription.setText(orderDescription);
        this.orderNumber.setText(orderId);
        this.timeOrderArrival.setText(orderArrivalTime);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        orderDescription = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOrderDescription = new javax.swing.JTextArea();
        orderInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        orderNumber = new javax.swing.JLabel();
        timeOrderArrival = new javax.swing.JLabel();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.125);
        jSplitPane1.setToolTipText("");

        txtOrderDescription.setColumns(20);
        txtOrderDescription.setRows(5);
        jScrollPane2.setViewportView(txtOrderDescription);

        javax.swing.GroupLayout orderDescriptionLayout = new javax.swing.GroupLayout(orderDescription);
        orderDescription.setLayout(orderDescriptionLayout);
        orderDescriptionLayout.setHorizontalGroup(
            orderDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderDescriptionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
        );
        orderDescriptionLayout.setVerticalGroup(
            orderDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderDescriptionLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setBottomComponent(orderDescription);

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel1.setText("Pedido:");

        orderNumber.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        orderNumber.setText("n° de pedido");

        timeOrderArrival.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        timeOrderArrival.setText("Hora de llegada del pedido");

        javax.swing.GroupLayout orderInfoLayout = new javax.swing.GroupLayout(orderInfo);
        orderInfo.setLayout(orderInfoLayout);
        orderInfoLayout.setHorizontalGroup(
            orderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(orderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderInfoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderNumber))
                    .addComponent(timeOrderArrival))
                .addGap(0, 129, Short.MAX_VALUE))
        );
        orderInfoLayout.setVerticalGroup(
            orderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderInfoLayout.createSequentialGroup()
                .addGroup(orderInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(orderNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeOrderArrival)
                .addGap(20, 20, 20))
        );

        jSplitPane1.setLeftComponent(orderInfo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel orderDescription;
    private javax.swing.JPanel orderInfo;
    private javax.swing.JLabel orderNumber;
    private javax.swing.JLabel timeOrderArrival;
    private javax.swing.JTextArea txtOrderDescription;
    // End of variables declaration//GEN-END:variables

    /**
     * Devuelve el label que debe mostrar el número del pedido.
     * @return the orderNumber
     */
    public javax.swing.JLabel getOrderNumber() {
        return orderNumber;
    }

    /**
     * Devuelve el label que debe mostrar el tiempo de llegada del pedido.
     * @return the timeOrderArrival
     */
    public javax.swing.JLabel getTimeOrderArrival() {
        return timeOrderArrival;
    }

    /**
     * Devuelve el text area que contiene la descripción del pedido.
     * @return the txtOrderDescription
     */
    public JTextArea getTxtOrderDescription() {
        return txtOrderDescription;
    }
}
